export const SECTION_ORDER = [
  "ENVELOPE",
  "HERO",
  "COUNTDOWN",
  "STORY",
  "TIMELINE",
  "GALLERY",
  "VENUE",
  "RSVP",
  "REGISTRY",
  "INSTAGRAM",
  "THANK_YOU",
];

export const THEMES = [
  {
    name: "Royal",
    slug: "royal",
    description: "Maroon, gold, and ivory — wax seals and flourish ornaments.",
    category: "traditional",
    colorPalette: {
      primary: "#7a2e2e",
      secondary: "#f3d9d9",
      accent: "#c9942a",
      background: "#faf3ea",
      foreground: "#3a1414",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: true, motif: "flourish" },
    isPremium: false,
    sortOrder: 0,
  },
  {
    name: "Traditional",
    slug: "traditional",
    description: "Deep red and gold with classic Indian motifs.",
    category: "traditional",
    colorPalette: {
      primary: "#8a1f1f",
      secondary: "#ffe8a0",
      accent: "#b8860b",
      background: "#fff8ec",
      foreground: "#2a1206",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: false, motif: "paisley" },
    isPremium: false,
    sortOrder: 1,
  },
  {
    name: "Luxury",
    slug: "luxury",
    description: "Black and gold with sharp, editorial typography.",
    category: "modern",
    colorPalette: {
      primary: "#111111",
      secondary: "#d4af37",
      accent: "#d4af37",
      background: "#0e0e0e",
      foreground: "#f5f0e6",
    },
    fontPairing: { display: "Playfair Display", body: "EB Garamond", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "geometric" },
    isPremium: true,
    sortOrder: 2,
  },
  {
    name: "Minimal",
    slug: "minimal",
    description: "Clean whitespace, quiet typography, understated elegance.",
    category: "minimal",
    colorPalette: {
      primary: "#1a1a1a",
      secondary: "#e5e5e5",
      accent: "#9a9a9a",
      background: "#ffffff",
      foreground: "#1a1a1a",
    },
    fontPairing: { display: "Playfair Display", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: false, motif: "none" },
    isPremium: false,
    sortOrder: 3,
  },
  {
    name: "Modern",
    slug: "modern",
    description: "Bold color blocking with contemporary sans-serif type.",
    category: "modern",
    colorPalette: {
      primary: "#1f2937",
      secondary: "#f472b6",
      accent: "#f472b6",
      background: "#fafafa",
      foreground: "#111827",
    },
    fontPairing: { display: "Inter", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "shapes" },
    isPremium: false,
    sortOrder: 4,
  },
  {
    name: "Temple",
    slug: "temple",
    description: "Stone and saffron tones inspired by temple architecture.",
    category: "traditional",
    colorPalette: {
      primary: "#9a4b1f",
      secondary: "#f2c14e",
      accent: "#7a2e2e",
      background: "#fdf1df",
      foreground: "#3a1f0d",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: false, motif: "temple-arch" },
    isPremium: true,
    sortOrder: 5,
  },
  {
    name: "Palace",
    slug: "palace",
    description: "Jewel-toned emerald and gold with regal framing.",
    category: "traditional",
    colorPalette: {
      primary: "#0f3d2e",
      secondary: "#c9942a",
      accent: "#c9942a",
      background: "#f6f4ea",
      foreground: "#0f2418",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "jali" },
    isPremium: true,
    sortOrder: 6,
  },
  {
    name: "Beach",
    slug: "beach",
    description: "Sandy neutrals and ocean blue for destination weddings.",
    category: "modern",
    colorPalette: {
      primary: "#1d4e6b",
      secondary: "#f4e3c1",
      accent: "#e0895f",
      background: "#fbf7ee",
      foreground: "#1d2b33",
    },
    fontPairing: { display: "Playfair Display", body: "EB Garamond", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: false, motif: "waves" },
    isPremium: false,
    sortOrder: 7,
  },
  {
    name: "Floral",
    slug: "floral",
    description: "Soft botanical illustrations in blush and sage.",
    category: "fusion",
    colorPalette: {
      primary: "#5c7a3a",
      secondary: "#f3d9d9",
      accent: "#c9942a",
      background: "#fdf8f2",
      foreground: "#2f3a20",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: false, motif: "botanical" },
    isPremium: false,
    sortOrder: 8,
  },
  {
    name: "Pastel",
    slug: "pastel",
    description: "Powder pink and lilac, soft and dreamy.",
    category: "fusion",
    colorPalette: {
      primary: "#a78bca",
      secondary: "#f9d5e5",
      accent: "#f9d5e5",
      background: "#fdfaff",
      foreground: "#3a2f4a",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: true, motif: "confetti" },
    isPremium: false,
    sortOrder: 9,
  },
  {
    name: "Dark Luxury",
    slug: "dark-luxury",
    description: "Charcoal and champagne gold with dramatic shimmer.",
    category: "modern",
    colorPalette: {
      primary: "#c9a24b",
      secondary: "#2a2a2a",
      accent: "#c9a24b",
      background: "#141414",
      foreground: "#f2ead8",
    },
    fontPairing: { display: "Playfair Display", body: "EB Garamond", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "shimmer" },
    isPremium: true,
    sortOrder: 10,
  },
  {
    name: "South Indian Kalyanam",
    slug: "kalyanam",
    description: "Kanjivaram maroon and temple gold for a classic South Indian wedding.",
    category: "traditional",
    colorPalette: {
      primary: "#6b1414",
      secondary: "#fbe6a6",
      accent: "#c98a1f",
      background: "#fff6e5",
      foreground: "#2c0f0a",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: false, motif: "temple-arch" },
    isPremium: true,
    sortOrder: 11,
  },
  {
    name: "Bengali Biye",
    slug: "bengali-biye",
    description: "Shakha-pola red and white with brushed gold accents.",
    category: "traditional",
    colorPalette: {
      primary: "#a3123a",
      secondary: "#fffaf3",
      accent: "#c9942a",
      background: "#fff8f0",
      foreground: "#3a0d18",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: false, motif: "paisley" },
    isPremium: false,
    sortOrder: 12,
  },
  {
    name: "Sikh Anand Karaj",
    slug: "anand-karaj",
    description: "Saffron and royal blue honoring a Sikh Anand Karaj ceremony.",
    category: "traditional",
    colorPalette: {
      primary: "#1c3f7a",
      secondary: "#ffd48a",
      accent: "#e8842c",
      background: "#fff8ec",
      foreground: "#1a1a2e",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "flourish" },
    isPremium: false,
    sortOrder: 13,
  },
  {
    name: "Nikah Elegance",
    slug: "nikah-elegance",
    description: "Emerald and gold with Islamic geometric framing for a Nikah.",
    category: "traditional",
    colorPalette: {
      primary: "#0b3d2e",
      secondary: "#e9d9a8",
      accent: "#c9942a",
      background: "#f7f5ea",
      foreground: "#0b1f16",
    },
    fontPairing: { display: "Playfair Display", body: "EB Garamond", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "jali" },
    isPremium: true,
    sortOrder: 14,
  },
  {
    name: "Mehendi Garden",
    slug: "mehendi-garden",
    description: "Henna green and marigold for sangeet and mehendi functions.",
    category: "traditional",
    colorPalette: {
      primary: "#3c6e2e",
      secondary: "#ffe08a",
      accent: "#e8842c",
      background: "#fbfbe5",
      foreground: "#1f2e12",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: false, motif: "botanical" },
    isPremium: false,
    sortOrder: 15,
  },
  {
    name: "Boho Modern",
    slug: "boho-modern",
    description: "Terracotta, sage, and cream with a relaxed contemporary feel.",
    category: "modern",
    colorPalette: {
      primary: "#a4633b",
      secondary: "#dbe3c6",
      accent: "#c98a5b",
      background: "#faf6ef",
      foreground: "#33291f",
    },
    fontPairing: { display: "Playfair Display", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: false, motif: "botanical" },
    isPremium: false,
    sortOrder: 16,
  },
  {
    name: "Scandi Modern",
    slug: "scandi-modern",
    description: "Muted blue-grey and white — quiet, airy, contemporary.",
    category: "modern",
    colorPalette: {
      primary: "#3d4f5c",
      secondary: "#e7ebee",
      accent: "#8a9aa5",
      background: "#ffffff",
      foreground: "#22292e",
    },
    fontPairing: { display: "Playfair Display", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: false, motif: "none" },
    isPremium: false,
    sortOrder: 17,
  },
  {
    name: "Neon Sangeet",
    slug: "neon-sangeet",
    description: "Hot pink and electric purple on black for a high-energy sangeet night.",
    category: "fusion",
    colorPalette: {
      primary: "#ff3d81",
      secondary: "#1a1025",
      accent: "#8b5cf6",
      background: "#100a17",
      foreground: "#fdf1ff",
    },
    fontPairing: { display: "Inter", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "shapes" },
    isPremium: true,
    sortOrder: 18,
  },
  {
    name: "Monochrome Modern",
    slug: "monochrome-modern",
    description: "Black, white, and grey — an editorial, gallery-clean look.",
    category: "modern",
    colorPalette: {
      primary: "#0a0a0a",
      secondary: "#f2f2f2",
      accent: "#5c5c5c",
      background: "#ffffff",
      foreground: "#0a0a0a",
    },
    fontPairing: { display: "Inter", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: false, motif: "geometric" },
    isPremium: false,
    sortOrder: 19,
  },
  {
    name: "Rustic Modern",
    slug: "rustic-modern",
    description: "Warm browns and olive with a contemporary countryside feel.",
    category: "modern",
    colorPalette: {
      primary: "#5b3a29",
      secondary: "#e6dcc6",
      accent: "#7c8a52",
      background: "#faf6ee",
      foreground: "#2b1d13",
    },
    fontPairing: { display: "Playfair Display", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: false, motif: "botanical" },
    isPremium: false,
    sortOrder: 20,
  },
];

// PDF-type themes for the "Download PDF" stylesheet — same shape as website
// themes, filtered by `type` so they never show up in the website picker.
export const PDF_THEMES = [
  {
    type: "PDF" as const,
    name: "Elegant Print",
    slug: "elegant-print",
    description: "A high-contrast, ink-friendly layout tuned for printing.",
    category: "classic",
    colorPalette: {
      primary: "#3a1414",
      secondary: "#e8d9c8",
      accent: "#8a1f1f",
      background: "#ffffff",
      foreground: "#1a1a1a",
    },
    fontPairing: { display: "Playfair Display", body: "EB Garamond", script: "Great Vibes" },
    isPremium: false,
    sortOrder: 0,
  },
];

// Gemini video prompt templates — {{placeholders}} are filled from the
// invitation's own captured details at generation time.
export const VIDEO_TEMPLATES = [
  {
    name: "Cinematic Teaser",
    slug: "cinematic-teaser",
    description: "A romantic, golden-hour teaser announcing the wedding date and venue.",
    aspectRatio: "9:16",
    durationSeconds: 15,
    promptTemplate:
      "A cinematic, romantic wedding invitation teaser for {{coupleNames}}, announcing their wedding on {{weddingDate}}. Warm golden-hour lighting, gentle camera movement, elegant typography overlay with the couple's names.",
    styleKeywords: ["golden hour", "romantic", "slow motion", "elegant"],
    geminiModel: "veo-3.0-generate-001",
    isPremium: false,
    sortOrder: 0,
  },
];

// No bundled "Studio Library" tracks: shipping placeholder mp3 URLs with no
// actual audio file behind them (the original state of this list) silently
// breaks music for anyone who picks one — the button shows up but nothing
// plays. Real tracks need real licensed audio files hosted somewhere; add
// them via /admin/music with a working URL once you have one.
export const MUSIC_TRACKS: {
  title: string;
  artist: string;
  url: string;
  mood: string;
  isPremium: boolean;
}[] = [];

// Homepage "see it in action" showcase — published, isDemo invitations so
// visitors can preview real invitations (in a phone mockup) before signing
// up. Re-running the seed only ever updates these by slug, never creates
// duplicates.
export const DEMO_INVITATIONS = [
  {
    slug: "demo-royal-wedding",
    themeSlug: "royal",
    brideName: "Aisha",
    groomName: "Rohan",
    weddingDate: "2026-12-12",
    venueName: "The Grand Palace",
    venueAddress: "Lake Pichola Road, Udaipur, Rajasthan",
    customMessage: "Join us as we begin our forever, with love, laughter, and a little royal drama.",
  },
  {
    slug: "demo-beach-wedding",
    themeSlug: "beach",
    brideName: "Meera",
    groomName: "Karthik",
    weddingDate: "2026-11-08",
    venueName: "Sunset Cove Resort",
    venueAddress: "Candolim Beach, Goa",
    customMessage: "Sand, sun, and forever — come celebrate with us by the sea.",
  },
  {
    slug: "demo-pastel-wedding",
    themeSlug: "pastel",
    brideName: "Priya",
    groomName: "Dev",
    weddingDate: "2027-02-14",
    venueName: "The Garden Terrace",
    venueAddress: "Whitefield, Bengaluru, Karnataka",
    customMessage: "Two hearts, one promise — join us for a wedding to remember.",
  },
] as const;
