export const SECTION_ORDER = [
  "ENVELOPE",
  "HERO",
  "COUNTDOWN",
  "STORY",
  "TIMELINE",
  "GALLERY",
  "VENUE",
  "RSVP",
  "REGISTRY",
  "INSTAGRAM",
  "THANK_YOU",
];

// Stock thumbnails so a freshly seeded catalogue shows photos rather than
// bare gradients. Admins can replace any of these from Manage Themes.
const THEME_THUMBNAILS: Record<string, string> = {
  royal: "1519741497674-611481863552",
  traditional: "1519225421980-715cb0215aed",
  luxury: "1544078751-58fee2d8b03f",
  minimal: "1511285560929-80b456fea0bc",
  modern: "1583939003579-730e3918a45a",
  temple: "1606216794074-735e91aa2c92",
  palace: "1583334026965-2a3f37c8e9fb",
  beach: "1520854221256-17451cc331bf",
  floral: "1465495976277-4387d4b0b4c6",
  pastel: "1521543387236-8c6f80e7d70e",
};

export function seedThumbnailFor(slug: string): string | undefined {
  const id = THEME_THUMBNAILS[slug];
  return id ? `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&q=80` : undefined;
}

export const THEMES = [
  {
    name: "Royal",
    slug: "royal",
    description: "Maroon, gold, and ivory — wax seals and flourish ornaments.",
    category: "traditional",
    colorPalette: {
      primary: "#7a2e2e",
      secondary: "#f3d9d9",
      accent: "#c9942a",
      background: "#faf3ea",
      foreground: "#3a1414",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: true, motif: "flourish" },
    eventCategory: "wedding",
    isPremium: false,
    sortOrder: 0,
  },
  {
    name: "Traditional",
    slug: "traditional",
    description: "Deep red and gold with classic Indian motifs.",
    category: "traditional",
    colorPalette: {
      primary: "#8a1f1f",
      secondary: "#ffe8a0",
      accent: "#b8860b",
      background: "#fff8ec",
      foreground: "#2a1206",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: false, motif: "paisley" },
    eventCategory: "wedding",
    isPremium: false,
    sortOrder: 1,
  },
  {
    name: "Luxury",
    slug: "luxury",
    description: "Black and gold with sharp, editorial typography.",
    category: "modern",
    colorPalette: {
      primary: "#111111",
      secondary: "#d4af37",
      accent: "#d4af37",
      background: "#0e0e0e",
      foreground: "#f5f0e6",
    },
    fontPairing: { display: "Playfair Display", body: "EB Garamond", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "geometric" },
    eventCategory: "wedding",
    isPremium: true,
    sortOrder: 2,
  },
  {
    name: "Minimal",
    slug: "minimal",
    description: "Clean whitespace, quiet typography, understated elegance.",
    category: "minimal",
    colorPalette: {
      primary: "#1a1a1a",
      secondary: "#e5e5e5",
      accent: "#9a9a9a",
      background: "#ffffff",
      foreground: "#1a1a1a",
    },
    fontPairing: { display: "Playfair Display", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: false, motif: "none" },
    eventCategory: "wedding",
    isPremium: false,
    sortOrder: 3,
  },
  {
    name: "Modern",
    slug: "modern",
    description: "Bold color blocking with contemporary sans-serif type.",
    category: "modern",
    colorPalette: {
      primary: "#1f2937",
      secondary: "#f472b6",
      accent: "#f472b6",
      background: "#fafafa",
      foreground: "#111827",
    },
    fontPairing: { display: "Inter", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "shapes" },
    eventCategory: "wedding",
    isPremium: false,
    sortOrder: 4,
  },
  {
    name: "Temple",
    slug: "temple",
    description: "Stone and saffron tones inspired by temple architecture.",
    category: "traditional",
    colorPalette: {
      primary: "#9a4b1f",
      secondary: "#f2c14e",
      accent: "#7a2e2e",
      background: "#fdf1df",
      foreground: "#3a1f0d",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: false, motif: "temple-arch" },
    eventCategory: "wedding",
    isPremium: true,
    sortOrder: 5,
  },
  {
    name: "Palace",
    slug: "palace",
    description: "Jewel-toned emerald and gold with regal framing.",
    category: "traditional",
    colorPalette: {
      primary: "#0f3d2e",
      secondary: "#c9942a",
      accent: "#c9942a",
      background: "#f6f4ea",
      foreground: "#0f2418",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "jali" },
    eventCategory: "wedding",
    isPremium: true,
    sortOrder: 6,
  },
  {
    name: "Beach",
    slug: "beach",
    description: "Sandy neutrals and ocean blue for destination weddings.",
    category: "modern",
    colorPalette: {
      primary: "#1d4e6b",
      secondary: "#f4e3c1",
      accent: "#e0895f",
      background: "#fbf7ee",
      foreground: "#1d2b33",
    },
    fontPairing: { display: "Playfair Display", body: "EB Garamond", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: false, motif: "waves" },
    eventCategory: "wedding",
    isPremium: false,
    sortOrder: 7,
  },
  {
    name: "Floral",
    slug: "floral",
    description: "Soft botanical illustrations in blush and sage.",
    category: "fusion",
    colorPalette: {
      primary: "#5c7a3a",
      secondary: "#f3d9d9",
      accent: "#c9942a",
      background: "#fdf8f2",
      foreground: "#2f3a20",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: false, motif: "botanical" },
    eventCategory: "wedding",
    isPremium: false,
    sortOrder: 8,
  },
  {
    name: "Pastel",
    slug: "pastel",
    description: "Powder pink and lilac, soft and dreamy.",
    category: "fusion",
    colorPalette: {
      primary: "#a78bca",
      secondary: "#f9d5e5",
      accent: "#f9d5e5",
      background: "#fdfaff",
      foreground: "#3a2f4a",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: true, motif: "confetti" },
    eventCategory: "wedding",
    isPremium: false,
    sortOrder: 9,
  },
  {
    name: "Dark Luxury",
    slug: "dark-luxury",
    description: "Charcoal and champagne gold with dramatic shimmer.",
    category: "modern",
    colorPalette: {
      primary: "#c9a24b",
      secondary: "#2a2a2a",
      accent: "#c9a24b",
      background: "#141414",
      foreground: "#f2ead8",
    },
    fontPairing: { display: "Playfair Display", body: "EB Garamond", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "shimmer" },
    eventCategory: "wedding",
    isPremium: true,
    sortOrder: 10,
  },
  {
    name: "South Indian Kalyanam",
    slug: "kalyanam",
    description: "Kanjivaram maroon and temple gold for a classic South Indian wedding.",
    category: "traditional",
    colorPalette: {
      primary: "#6b1414",
      secondary: "#fbe6a6",
      accent: "#c98a1f",
      background: "#fff6e5",
      foreground: "#2c0f0a",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: false, motif: "temple-arch" },
    eventCategory: "wedding",
    isPremium: true,
    sortOrder: 11,
  },
  {
    name: "Bengali Biye",
    slug: "bengali-biye",
    description: "Shakha-pola red and white with brushed gold accents.",
    category: "traditional",
    colorPalette: {
      primary: "#a3123a",
      secondary: "#fffaf3",
      accent: "#c9942a",
      background: "#fff8f0",
      foreground: "#3a0d18",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: false, motif: "paisley" },
    eventCategory: "wedding",
    isPremium: false,
    sortOrder: 12,
  },
  {
    name: "Sikh Anand Karaj",
    slug: "anand-karaj",
    description: "Saffron and royal blue honoring a Sikh Anand Karaj ceremony.",
    category: "traditional",
    colorPalette: {
      primary: "#1c3f7a",
      secondary: "#ffd48a",
      accent: "#e8842c",
      background: "#fff8ec",
      foreground: "#1a1a2e",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "flourish" },
    eventCategory: "wedding",
    isPremium: false,
    sortOrder: 13,
  },
  {
    name: "Nikah Elegance",
    slug: "nikah-elegance",
    description: "Emerald and gold with Islamic geometric framing for a Nikah.",
    category: "traditional",
    colorPalette: {
      primary: "#0b3d2e",
      secondary: "#e9d9a8",
      accent: "#c9942a",
      background: "#f7f5ea",
      foreground: "#0b1f16",
    },
    fontPairing: { display: "Playfair Display", body: "EB Garamond", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "jali" },
    eventCategory: "wedding",
    isPremium: true,
    sortOrder: 14,
  },
  {
    name: "Mehendi Garden",
    slug: "mehendi-garden",
    description: "Henna green and marigold for sangeet and mehendi functions.",
    category: "traditional",
    colorPalette: {
      primary: "#3c6e2e",
      secondary: "#ffe08a",
      accent: "#e8842c",
      background: "#fbfbe5",
      foreground: "#1f2e12",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: false, motif: "botanical" },
    eventCategory: "wedding",
    isPremium: false,
    sortOrder: 15,
  },
  {
    name: "Boho Modern",
    slug: "boho-modern",
    description: "Terracotta, sage, and cream with a relaxed contemporary feel.",
    category: "modern",
    colorPalette: {
      primary: "#a4633b",
      secondary: "#dbe3c6",
      accent: "#c98a5b",
      background: "#faf6ef",
      foreground: "#33291f",
    },
    fontPairing: { display: "Playfair Display", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: false, motif: "botanical" },
    eventCategory: "wedding",
    isPremium: false,
    sortOrder: 16,
  },
  {
    name: "Scandi Modern",
    slug: "scandi-modern",
    description: "Muted blue-grey and white — quiet, airy, contemporary.",
    category: "modern",
    colorPalette: {
      primary: "#3d4f5c",
      secondary: "#e7ebee",
      accent: "#8a9aa5",
      background: "#ffffff",
      foreground: "#22292e",
    },
    fontPairing: { display: "Playfair Display", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: false, motif: "none" },
    eventCategory: "wedding",
    isPremium: false,
    sortOrder: 17,
  },
  {
    name: "Neon Sangeet",
    slug: "neon-sangeet",
    description: "Hot pink and electric purple on black for a high-energy sangeet night.",
    category: "fusion",
    colorPalette: {
      primary: "#ff3d81",
      secondary: "#1a1025",
      accent: "#8b5cf6",
      background: "#100a17",
      foreground: "#fdf1ff",
    },
    fontPairing: { display: "Inter", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "shapes" },
    eventCategory: "wedding",
    isPremium: true,
    sortOrder: 18,
  },
  {
    name: "Monochrome Modern",
    slug: "monochrome-modern",
    description: "Black, white, and grey — an editorial, gallery-clean look.",
    category: "modern",
    colorPalette: {
      primary: "#0a0a0a",
      secondary: "#f2f2f2",
      accent: "#5c5c5c",
      background: "#ffffff",
      foreground: "#0a0a0a",
    },
    fontPairing: { display: "Inter", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: false, motif: "geometric" },
    eventCategory: "wedding",
    isPremium: false,
    sortOrder: 19,
  },
  {
    name: "Rustic Modern",
    slug: "rustic-modern",
    description: "Warm browns and olive with a contemporary countryside feel.",
    category: "modern",
    colorPalette: {
      primary: "#5b3a29",
      secondary: "#e6dcc6",
      accent: "#7c8a52",
      background: "#faf6ee",
      foreground: "#2b1d13",
    },
    fontPairing: { display: "Playfair Display", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: false, motif: "botanical" },
    eventCategory: "wedding",
    isPremium: false,
    sortOrder: 20,
  },
];

// PDF-type themes for the "Download PDF" stylesheet — same shape as website
// themes, filtered by `type` so they never show up in the website picker.
// These are print *layouts*, not per-celebration designs: `decorAssets.pdfLayout`
// picks which one the renderer draws ("classic", "photo", "story"), and the
// copy on the page comes from the invitation's own event category. So they are
// never filtered by eventCategory — a birthday and a wedding can both print as
// a Photo Card.
export const PDF_THEMES = [
  {
    type: "PDF" as const,
    name: "Elegant Print",
    slug: "elegant-print",
    description: "A high-contrast, ink-friendly layout tuned for printing.",
    category: "classic",
    colorPalette: {
      primary: "#3a1414",
      secondary: "#e8d9c8",
      accent: "#8a1f1f",
      background: "#ffffff",
      foreground: "#1a1a1a",
    },
    fontPairing: { display: "Playfair Display", body: "EB Garamond", script: "Great Vibes" },
    decorAssets: { pdfLayout: "classic" },
    isPremium: false,
    sortOrder: 0,
  },
  {
    type: "PDF" as const,
    name: "Photo Card",
    slug: "photo-card",
    description: "A full-bleed cover photo with the details set over it.",
    category: "modern",
    colorPalette: {
      primary: "#1f2937",
      secondary: "#e7ebee",
      accent: "#b08b4f",
      background: "#ffffff",
      foreground: "#1a1a1a",
    },
    fontPairing: { display: "Playfair Display", body: "Inter", script: "Great Vibes" },
    decorAssets: { pdfLayout: "photo" },
    isPremium: false,
    sortOrder: 1,
  },
  {
    type: "PDF" as const,
    name: "Photo Story",
    slug: "photo-story",
    description: "Cover photo, full schedule, and a gallery page of your photos.",
    category: "classic",
    colorPalette: {
      primary: "#7a2e2e",
      secondary: "#f3d9d9",
      accent: "#c9942a",
      background: "#fffaf4",
      foreground: "#2a1a14",
    },
    fontPairing: { display: "Playfair Display", body: "EB Garamond", script: "Great Vibes" },
    decorAssets: { pdfLayout: "story" },
    isPremium: false,
    sortOrder: 2,
  },
];

// Gemini video prompt templates — {{placeholders}} are filled from the
// invitation's own captured details at generation time.
export const VIDEO_TEMPLATES = [
  {
    name: "Cinematic Teaser",
    slug: "cinematic-teaser",
    description: "A romantic, golden-hour teaser announcing the wedding date and venue.",
    aspectRatio: "9:16",
    durationSeconds: 15,
    promptTemplate:
      "A cinematic, romantic wedding invitation teaser for {{coupleNames}}, announcing their wedding on {{weddingDate}}. Warm golden-hour lighting, gentle camera movement, elegant typography overlay with the couple's names.",
    styleKeywords: ["golden hour", "romantic", "slow motion", "elegant"],
    geminiModel: "auto",
    isPremium: false,
    sortOrder: 0,
  },
];

// No bundled "Studio Library" tracks: shipping placeholder mp3 URLs with no
// actual audio file behind them (the original state of this list) silently
// breaks music for anyone who picks one — the button shows up but nothing
// plays. Real tracks need real licensed audio files hosted somewhere; add
// them via /admin/library/music with a working URL once you have one.
export const MUSIC_TRACKS: {
  title: string;
  artist: string;
  url: string;
  mood: string;
  isPremium: boolean;
}[] = [];

// Homepage "see it in action" showcase — published, isDemo invitations so
// visitors can preview real invitations (in a phone mockup) before signing
// up. Re-running the seed only ever updates these by slug, never creates
// duplicates.
export const DEMO_INVITATIONS = [
  {
    slug: "demo-royal-wedding",
    eventCategory: "wedding",
    themeSlug: "royal",
    brideName: "Aisha",
    groomName: "Rohan",
    weddingDate: "2026-12-12",
    venueName: "The Grand Palace",
    venueAddress: "Lake Pichola Road, Udaipur, Rajasthan",
    customMessage: "Join us as we begin our forever, with love, laughter, and a little royal drama.",
  },
  {
    slug: "demo-beach-wedding",
    eventCategory: "wedding",
    themeSlug: "beach",
    brideName: "Meera",
    groomName: "Karthik",
    weddingDate: "2026-11-08",
    venueName: "Sunset Cove Resort",
    venueAddress: "Candolim Beach, Goa",
    customMessage: "Sand, sun, and forever — come celebrate with us by the sea.",
  },
  {
    slug: "demo-pastel-wedding",
    eventCategory: "wedding",
    themeSlug: "pastel",
    brideName: "Priya",
    groomName: "Dev",
    weddingDate: "2027-02-14",
    venueName: "The Garden Terrace",
    venueAddress: "Whitefield, Bengaluru, Karnataka",
    customMessage: "Two hearts, one promise — join us for a wedding to remember.",
  },
  {
    slug: "demo-birthday",
    eventCategory: "birthday",
    themeSlug: "confetti-pop",
    brideName: "Aarav",
    groomName: "The Shah Family",
    weddingDate: "2026-09-19",
    venueName: "The Terrace Cafe",
    venueAddress: "Koregaon Park, Pune, Maharashtra",
    customMessage: "Ten years old and counting — come eat cake with us.",
  },
  {
    slug: "demo-housewarming",
    eventCategory: "housewarming",
    themeSlug: "griha-pravesh",
    brideName: "Deshmukh",
    groomName: "Sunita & Ravi",
    weddingDate: "2026-10-03",
    venueName: "Shanti Nivas",
    venueAddress: "Plot 14, Sector 8, Nashik, Maharashtra",
    customMessage: "Our first lamp is lit — please come bless our new home.",
  },
  {
    slug: "demo-baby-shower",
    eventCategory: "baby-shower",
    themeSlug: "godh-bharai",
    brideName: "Ananya",
    groomName: "Vikram",
    weddingDate: "2026-08-30",
    venueName: "Rose Garden Hall",
    venueAddress: "Jayanagar, Bengaluru, Karnataka",
    customMessage: "Sweets, songs, and blessings before our little one arrives.",
  },
] as const;

// Colourways per theme: same design, different palette. Keyed by theme slug;
// a theme with no entry simply ships in its own default palette. Each entry
// mirrors the shape of Theme.colorPalette.
export const THEME_COLORWAYS: Record<
  string,
  { name: string; slug: string; colorPalette: Record<string, string> }[]
> = {
  royal: [
    {
      name: "Maroon & Gold",
      slug: "maroon-gold",
      colorPalette: {
        primary: "#7a2e2e",
        secondary: "#f3d9d9",
        accent: "#c9942a",
        background: "#faf3ea",
        foreground: "#3a1414",
      },
    },
    {
      name: "Emerald & Gold",
      slug: "emerald-gold",
      colorPalette: {
        primary: "#1f5140",
        secondary: "#d8e8e0",
        accent: "#c9942a",
        background: "#f6faf7",
        foreground: "#12362a",
      },
    },
    {
      name: "Midnight & Rose",
      slug: "midnight-rose",
      colorPalette: {
        primary: "#2b2f52",
        secondary: "#dcdff0",
        accent: "#c98a9a",
        background: "#f7f7fb",
        foreground: "#1a1d33",
      },
    },
  ],
  traditional: [
    {
      name: "Kumkum Red",
      slug: "kumkum-red",
      colorPalette: {
        primary: "#8f2f24",
        secondary: "#f6dcd6",
        accent: "#d9a520",
        background: "#fdf6ee",
        foreground: "#3d1410",
      },
    },
    {
      name: "Turmeric",
      slug: "turmeric",
      colorPalette: {
        primary: "#a8720f",
        secondary: "#f7e6c4",
        accent: "#7a2e2e",
        background: "#fdf8ee",
        foreground: "#3f2a08",
      },
    },
    {
      name: "Peacock",
      slug: "peacock",
      colorPalette: {
        primary: "#14566b",
        secondary: "#cfe6ed",
        accent: "#d9a520",
        background: "#f3fafc",
        foreground: "#0b3140",
      },
    },
  ],
  beach: [
    {
      name: "Ocean",
      slug: "ocean",
      colorPalette: {
        primary: "#2e6a7a",
        secondary: "#d6ecf1",
        accent: "#8fd0d8",
        background: "#f2f8fa",
        foreground: "#12333c",
      },
    },
    {
      name: "Sunset",
      slug: "sunset",
      colorPalette: {
        primary: "#b4573c",
        secondary: "#f8dfd3",
        accent: "#e8a76a",
        background: "#fdf6f1",
        foreground: "#4a1e12",
      },
    },
    {
      name: "Palm",
      slug: "palm",
      colorPalette: {
        primary: "#3d6b46",
        secondary: "#dcebdd",
        accent: "#c8b06a",
        background: "#f5faf5",
        foreground: "#1e3a23",
      },
    },
  ],
  floral: [
    {
      name: "Blush",
      slug: "blush",
      colorPalette: {
        primary: "#a04a6a",
        secondary: "#f7dce6",
        accent: "#f0c0d0",
        background: "#fdf3f7",
        foreground: "#4a1c2c",
      },
    },
    {
      name: "Lavender",
      slug: "lavender",
      colorPalette: {
        primary: "#6f5a9a",
        secondary: "#e4dcf2",
        accent: "#c0aee0",
        background: "#f8f5fd",
        foreground: "#2f2450",
      },
    },
    {
      name: "Marigold",
      slug: "marigold",
      colorPalette: {
        primary: "#c07a12",
        secondary: "#fae5c2",
        accent: "#e0a93c",
        background: "#fdf8ef",
        foreground: "#4c2f04",
      },
    },
  ],
  minimal: [
    {
      name: "Ink",
      slug: "ink",
      colorPalette: {
        primary: "#3a3a3a",
        secondary: "#e6e4e0",
        accent: "#b9a179",
        background: "#f7f5f2",
        foreground: "#1c1c1c",
      },
    },
    {
      name: "Sage",
      slug: "sage",
      colorPalette: {
        primary: "#5c6f5c",
        secondary: "#e2e9e0",
        accent: "#a8b89f",
        background: "#f6f8f5",
        foreground: "#2b352b",
      },
    },
    {
      name: "Sand",
      slug: "sand",
      colorPalette: {
        primary: "#8a7350",
        secondary: "#f0e7d8",
        accent: "#c9b38c",
        background: "#faf6ee",
        foreground: "#3b3020",
      },
    },
  ],
  pastel: [
    {
      name: "Lilac",
      slug: "lilac",
      colorPalette: {
        primary: "#8a6a9a",
        secondary: "#ece0f2",
        accent: "#e0c8e8",
        background: "#faf6fb",
        foreground: "#3d2b47",
      },
    },
    {
      name: "Mint",
      slug: "mint",
      colorPalette: {
        primary: "#4e8a7a",
        secondary: "#d9efe7",
        accent: "#a8ddcd",
        background: "#f4fbf8",
        foreground: "#20443a",
      },
    },
    {
      name: "Peach",
      slug: "peach",
      colorPalette: {
        primary: "#c4735a",
        secondary: "#fae0d5",
        accent: "#f0b79c",
        background: "#fdf6f2",
        foreground: "#4f2618",
      },
    },
  ],
};

// ---------------------------------------------------------------------------
// Designs for the other celebrations
// ---------------------------------------------------------------------------

// A few designs per event category, each shipping its own copy so a
// birthday invite reads like a birthday invite before anyone types a word.
// `content` matches the EventCategoryContent shape in event-categories.ts;
// `{names}`, `{date}`, and `{venue}` are filled in at save time. A theme
// that leaves `content` out falls back to its category's default copy.
export const CATEGORY_THEMES = [
  // --- Ring Ceremony -------------------------------------------------------
  {
    name: "Ring Blush",
    slug: "ring-blush",
    description: "Blush pink and rose gold, soft enough for an intimate ring exchange.",
    category: "fusion",
    eventCategory: "ring-ceremony",
    colorPalette: {
      primary: "#a8536b",
      secondary: "#f8dee6",
      accent: "#c99a6a",
      background: "#fdf6f8",
      foreground: "#43202b",
    },
    fontPairing: {
      display: "Playfair Display",
      body: "Cormorant Garamond",
      script: "Great Vibes",
    },
    decorAssets: { petals: true, sparkles: true, motif: "botanical" },
    content: {
      eyebrow: "Ring Ceremony",
      heroHeadline: "Two Rings, One Promise",
      heroSubline: "Be there when the rings go on — {date}",
      invitationLetter:
        "Our families warmly invite you to the ring ceremony of {names} on {date}.{venue} Come share the moment two families become one.",
      storyHeadline: "The First Yes",
      thankYou: "Thank you for blessing the beginning of our story.",
      hashtagSuffix: "RingCeremony",
    },
    isPremium: false,
    sortOrder: 100,
  },
  {
    name: "Ring Royal",
    slug: "ring-royal",
    description: "Maroon and gold with regal framing for a large family ceremony.",
    category: "traditional",
    eventCategory: "ring-ceremony",
    colorPalette: {
      primary: "#7a2e2e",
      secondary: "#f6e3c0",
      accent: "#c9942a",
      background: "#fff8ee",
      foreground: "#331312",
    },
    fontPairing: {
      display: "Playfair Display",
      body: "Cormorant Garamond",
      script: "Great Vibes",
    },
    decorAssets: { petals: true, sparkles: false, motif: "flourish" },
    content: {
      eyebrow: "Ring Ceremony",
      heroHeadline: "With The Blessings Of Our Families",
      heroSubline: "The rings are exchanged on {date}",
      invitationLetter:
        "With the blessings of our elders, we invite you to the ring ceremony of {names} on {date}.{venue} Your presence will make the day complete.",
      storyHeadline: "A New Bond",
      thankYou: "We are grateful for your blessings and good wishes.",
      hashtagSuffix: "RingCeremony",
    },
    isPremium: false,
    sortOrder: 101,
  },
  {
    name: "Ring Minimal",
    slug: "ring-minimal",
    description: "Ivory and slate — one line of type and a lot of quiet space.",
    category: "minimal",
    eventCategory: "ring-ceremony",
    colorPalette: {
      primary: "#33414d",
      secondary: "#e9ecef",
      accent: "#a08a6a",
      background: "#ffffff",
      foreground: "#1e262c",
    },
    fontPairing: { display: "Playfair Display", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: false, motif: "none" },
    content: {
      eyebrow: "Ring Ceremony",
      heroHeadline: "Save The Evening",
      heroSubline: "Rings, dinner, and the people who matter — {date}",
      invitationLetter:
        "We'd love you with us for the ring ceremony of {names} on {date}.{venue} Small gathering, big moment.",
      storyHeadline: "Just Us",
      thankYou: "Thank you for keeping the evening for us.",
      hashtagSuffix: "RingCeremony",
    },
    isPremium: false,
    sortOrder: 102,
  },

  // --- Engagement ----------------------------------------------------------
  {
    name: "Sagai Gold",
    slug: "sagai-gold",
    description: "Marigold and deep red for a traditional engagement.",
    category: "traditional",
    eventCategory: "engagement",
    colorPalette: {
      primary: "#8f2f24",
      secondary: "#fbe3b4",
      accent: "#d9a520",
      background: "#fff9ed",
      foreground: "#3a140f",
    },
    fontPairing: {
      display: "Playfair Display",
      body: "Cormorant Garamond",
      script: "Great Vibes",
    },
    decorAssets: { petals: true, sparkles: true, motif: "paisley" },
    content: {
      eyebrow: "Engagement Invitation",
      heroHeadline: "The Sagai Is Set",
      heroSubline: "Join both families as we celebrate — {date}",
      invitationLetter:
        "Both our families joyfully invite you to the engagement of {names} on {date}.{venue} Come bless the couple as they promise the years ahead.",
      storyHeadline: "How It Started",
      thankYou: "Your blessings mean more to us than anything we could unwrap.",
      hashtagSuffix: "Engagement",
    },
    isPremium: false,
    sortOrder: 110,
  },
  {
    name: "Champagne Night",
    slug: "champagne-night",
    description: "Charcoal and champagne gold for an evening engagement party.",
    category: "modern",
    eventCategory: "engagement",
    colorPalette: {
      primary: "#c9a24b",
      secondary: "#242424",
      accent: "#c9a24b",
      background: "#151515",
      foreground: "#f3ead9",
    },
    fontPairing: {
      display: "Playfair Display",
      body: "EB Garamond",
      script: "Great Vibes",
    },
    decorAssets: { petals: false, sparkles: true, motif: "shimmer" },
    content: {
      eyebrow: "Engagement Invitation",
      heroHeadline: "We Said Yes",
      heroSubline: "Drinks, dinner, and one very good announcement — {date}",
      invitationLetter:
        "We're engaged, and we'd love you there when we say it out loud. Join us for the engagement of {names} on {date}.{venue}",
      storyHeadline: "The Story So Far",
      thankYou: "Thank you for raising a glass with us.",
      hashtagSuffix: "Engagement",
    },
    isPremium: true,
    sortOrder: 111,
  },
  {
    name: "Rose Promise",
    slug: "rose-promise",
    description: "Blush, sage, and soft botanicals for a daytime engagement.",
    category: "fusion",
    eventCategory: "engagement",
    colorPalette: {
      primary: "#9b5566",
      secondary: "#f6e0e4",
      accent: "#8fa07a",
      background: "#fdf7f6",
      foreground: "#3c2229",
    },
    fontPairing: {
      display: "Playfair Display",
      body: "Cormorant Garamond",
      script: "Great Vibes",
    },
    decorAssets: { petals: true, sparkles: false, motif: "botanical" },
    content: {
      eyebrow: "Engagement Invitation",
      heroHeadline: "A Promise, Kept",
      heroSubline: "Celebrate our engagement in the garden — {date}",
      invitationLetter:
        "Together with our families, we invite you to the engagement of {names} on {date}.{venue} An afternoon of flowers, food, and one very happy yes.",
      storyHeadline: "How It Started",
      thankYou: "Grateful for everyone who has loved us this far.",
      hashtagSuffix: "Engagement",
    },
    isPremium: false,
    sortOrder: 112,
  },

  // --- Birthday ------------------------------------------------------------
  {
    name: "Confetti Pop",
    slug: "confetti-pop",
    description: "Bright confetti colours for a birthday that isn't shy.",
    category: "modern",
    eventCategory: "birthday",
    colorPalette: {
      primary: "#e4572e",
      secondary: "#ffe3d1",
      accent: "#2e86ab",
      background: "#fffaf5",
      foreground: "#2b1a12",
    },
    fontPairing: { display: "Inter", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "confetti" },
    content: {
      eyebrow: "Birthday Invitation",
      heroHeadline: "It's Party Time",
      heroSubline: "Cake, music, and you — {date}",
      invitationLetter:
        "You're invited to the birthday party of {names} on {date}.{venue} Bring your appetite; the cake is handled.",
      storyHeadline: "Another Year",
      thankYou: "Thank you for making the day loud in the best way.",
      hashtagSuffix: "Birthday",
    },
    isPremium: false,
    sortOrder: 120,
  },
  {
    name: "Balloon Party",
    slug: "balloon-party",
    description: "Soft pastels and balloons — made for a little one's birthday.",
    category: "fusion",
    eventCategory: "birthday",
    colorPalette: {
      primary: "#5aa9c9",
      secondary: "#ffe9f1",
      accent: "#f5b942",
      background: "#fbfdff",
      foreground: "#233642",
    },
    fontPairing: { display: "Inter", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "shapes" },
    content: {
      eyebrow: "Birthday Invitation",
      heroHeadline: "Come Play With Us",
      heroSubline: "Balloons, games, and cake — {date}",
      invitationLetter:
        "We're throwing a party for {names} on {date}.{venue} Games, balloons, and enough cake for everyone — please come.",
      storyHeadline: "Growing Up",
      thankYou: "Thank you for celebrating our favourite little person.",
      hashtagSuffix: "Birthday",
    },
    isPremium: false,
    sortOrder: 121,
  },
  {
    name: "Midnight Gold",
    slug: "midnight-gold",
    description: "Black and gold for a milestone birthday dinner.",
    category: "modern",
    eventCategory: "birthday",
    colorPalette: {
      primary: "#d4af37",
      secondary: "#1e1e1e",
      accent: "#d4af37",
      background: "#101010",
      foreground: "#f5efe1",
    },
    fontPairing: { display: "Playfair Display", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "shimmer" },
    content: {
      eyebrow: "Birthday Invitation",
      heroHeadline: "A Night To Mark It",
      heroSubline: "Dinner, drinks, and a milestone worth the fuss — {date}",
      invitationLetter:
        "Please join us for an evening celebrating {names} on {date}.{venue} Good food, good company, and a birthday worth dressing up for.",
      storyHeadline: "The Years So Far",
      thankYou: "Thank you for spending the evening with us.",
      hashtagSuffix: "Birthday",
    },
    isPremium: true,
    sortOrder: 122,
  },

  // --- Naming --------------------------------------------------------------
  {
    name: "Little Blessing",
    slug: "little-blessing",
    description: "Mint and cream, gentle as the occasion deserves.",
    category: "fusion",
    eventCategory: "naming",
    colorPalette: {
      primary: "#4e8a7a",
      secondary: "#dcefe8",
      accent: "#e0b96a",
      background: "#f8fdfb",
      foreground: "#20443a",
    },
    fontPairing: {
      display: "Playfair Display",
      body: "Cormorant Garamond",
      script: "Great Vibes",
    },
    decorAssets: { petals: true, sparkles: true, motif: "botanical" },
    content: {
      eyebrow: "Naming Ceremony",
      heroHeadline: "A Name, At Last",
      heroSubline: "Come bless our little one — {date}",
      invitationLetter:
        "With hearts full of joy, we invite you to the naming ceremony of {names} on {date}.{venue} Come shower our little one with blessings.",
      storyHeadline: "Our Little One",
      thankYou: "Your blessings are the best gift our family could receive.",
      hashtagSuffix: "NamingCeremony",
    },
    isPremium: false,
    sortOrder: 130,
  },
  {
    name: "Naamkaran Gold",
    slug: "naamkaran-gold",
    description: "Saffron and gold for a traditional naamkaran at home.",
    category: "traditional",
    eventCategory: "naming",
    colorPalette: {
      primary: "#b4611a",
      secondary: "#fbe4bd",
      accent: "#c9942a",
      background: "#fff8ec",
      foreground: "#3d200a",
    },
    fontPairing: {
      display: "Playfair Display",
      body: "Cormorant Garamond",
      script: "Great Vibes",
    },
    decorAssets: { petals: true, sparkles: false, motif: "paisley" },
    content: {
      eyebrow: "Naamkaran",
      heroHeadline: "Our Little One Has A Name",
      heroSubline: "Join the naamkaran ceremony — {date}",
      invitationLetter:
        "With the blessings of our elders, our family invites you to the naming ceremony of {names} on {date}.{venue} Please join us for the rituals and the lunch that follows.",
      storyHeadline: "Our Little One",
      thankYou: "Thank you for blessing the newest member of our family.",
      hashtagSuffix: "Naamkaran",
    },
    isPremium: false,
    sortOrder: 131,
  },
  {
    name: "Cloud Nine",
    slug: "cloud-nine",
    description: "Sky blue and white, quiet and modern.",
    category: "minimal",
    eventCategory: "naming",
    colorPalette: {
      primary: "#41739c",
      secondary: "#e4eef6",
      accent: "#9db8cc",
      background: "#ffffff",
      foreground: "#1f303d",
    },
    fontPairing: { display: "Playfair Display", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "none" },
    content: {
      eyebrow: "Naming Ceremony",
      heroHeadline: "Say Hello",
      heroSubline: "We're naming our little one — {date}",
      invitationLetter:
        "We'd love you with us as we name our little one, {names}, on {date}.{venue} A short ceremony, and then brunch.",
      storyHeadline: "Our Little One",
      thankYou: "Thank you for being part of our first big day together.",
      hashtagSuffix: "NamingCeremony",
    },
    isPremium: false,
    sortOrder: 132,
  },

  // --- Anniversary ---------------------------------------------------------
  {
    name: "Golden Years",
    slug: "golden-years",
    description: "Deep gold and ivory for a milestone anniversary.",
    category: "traditional",
    eventCategory: "anniversary",
    colorPalette: {
      primary: "#a8801f",
      secondary: "#f6e8c6",
      accent: "#7a2e2e",
      background: "#fffaef",
      foreground: "#39290a",
    },
    fontPairing: {
      display: "Playfair Display",
      body: "Cormorant Garamond",
      script: "Great Vibes",
    },
    decorAssets: { petals: true, sparkles: true, motif: "flourish" },
    content: {
      eyebrow: "Anniversary Invitation",
      heroHeadline: "All These Golden Years",
      heroSubline: "Celebrate the milestone with us — {date}",
      invitationLetter:
        "Our family invites you to celebrate the wedding anniversary of {names} on {date}.{venue} Come raise a toast to a marriage worth every year.",
      storyHeadline: "All These Years",
      thankYou: "Thank you for the years you've spent alongside us.",
      hashtagSuffix: "Anniversary",
    },
    isPremium: true,
    sortOrder: 140,
  },
  {
    name: "Silver Jubilee",
    slug: "silver-jubilee",
    description: "Navy and silver, formal and understated.",
    category: "minimal",
    eventCategory: "anniversary",
    colorPalette: {
      primary: "#2c3e56",
      secondary: "#e6eaef",
      accent: "#9aa7b5",
      background: "#ffffff",
      foreground: "#1a232f",
    },
    fontPairing: { display: "Playfair Display", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "none" },
    content: {
      eyebrow: "Anniversary Invitation",
      heroHeadline: "Twenty-Five And Counting",
      heroSubline: "Dinner to mark the years — {date}",
      invitationLetter:
        "Please join us for dinner as we celebrate the anniversary of {names} on {date}.{venue} No gifts — just come.",
      storyHeadline: "All These Years",
      thankYou: "Thank you for being there through all of it.",
      hashtagSuffix: "Anniversary",
    },
    isPremium: false,
    sortOrder: 141,
  },
  {
    name: "Evergreen Love",
    slug: "evergreen-love",
    description: "Sage and blush for a relaxed anniversary lunch.",
    category: "fusion",
    eventCategory: "anniversary",
    colorPalette: {
      primary: "#5c7a3a",
      secondary: "#f2dfe2",
      accent: "#c0925f",
      background: "#fbfaf5",
      foreground: "#2c3820",
    },
    fontPairing: {
      display: "Playfair Display",
      body: "Cormorant Garamond",
      script: "Great Vibes",
    },
    decorAssets: { petals: true, sparkles: false, motif: "botanical" },
    content: {
      eyebrow: "Anniversary Invitation",
      heroHeadline: "Still Going Strong",
      heroSubline: "Lunch, family, and one more year — {date}",
      invitationLetter:
        "We'd love you with us as we celebrate the anniversary of {names} on {date}.{venue} An afternoon with the people who have been there all along.",
      storyHeadline: "All These Years",
      thankYou: "Thank you for filling these years with company.",
      hashtagSuffix: "Anniversary",
    },
    isPremium: false,
    sortOrder: 142,
  },

  // --- Housewarming --------------------------------------------------------
  {
    name: "Griha Pravesh",
    slug: "griha-pravesh",
    description: "Marigold and vermilion for the traditional first entry.",
    category: "traditional",
    eventCategory: "housewarming",
    colorPalette: {
      primary: "#b4451a",
      secondary: "#fbe0b0",
      accent: "#d9a520",
      background: "#fff8ea",
      foreground: "#3b1a0c",
    },
    fontPairing: {
      display: "Playfair Display",
      body: "Cormorant Garamond",
      script: "Great Vibes",
    },
    decorAssets: { petals: true, sparkles: false, motif: "temple-arch" },
    content: {
      eyebrow: "Griha Pravesh",
      heroHeadline: "Our First Step Inside",
      heroSubline: "Join the griha pravesh puja — {date}",
      invitationLetter:
        "With gratitude, the {names} family invites you to the griha pravesh of our new home on {date}.{venue} Please join us for the puja and the lunch that follows.",
      storyHeadline: "Our New Home",
      thankYou: "Your blessings turn a house into a home.",
      hashtagSuffix: "GrihaPravesh",
    },
    isPremium: false,
    sortOrder: 150,
  },
  {
    name: "New Nest",
    slug: "new-nest",
    description: "Terracotta and sage — a modern, relaxed housewarming.",
    category: "modern",
    eventCategory: "housewarming",
    colorPalette: {
      primary: "#a4633b",
      secondary: "#e2e8d5",
      accent: "#7c8a52",
      background: "#faf7f1",
      foreground: "#33261c",
    },
    fontPairing: { display: "Playfair Display", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: false, motif: "botanical" },
    content: {
      eyebrow: "Housewarming",
      heroHeadline: "We've Found Our Place",
      heroSubline: "Come see the new house — {date}",
      invitationLetter:
        "The {names} family is finally unpacked, and we'd love to show you around on {date}.{venue} Come eat, look around, and stay a while.",
      storyHeadline: "Our New Home",
      thankYou: "Thank you for being among the first through our door.",
      hashtagSuffix: "Housewarming",
    },
    isPremium: false,
    sortOrder: 151,
  },
  {
    name: "Diya Glow",
    slug: "diya-glow",
    description: "Warm amber and deep brown, lit like an evening lamp.",
    category: "fusion",
    eventCategory: "housewarming",
    colorPalette: {
      primary: "#8a4b12",
      secondary: "#f7e2bf",
      accent: "#d98c2b",
      background: "#fdf6e9",
      foreground: "#33200c",
    },
    fontPairing: {
      display: "Playfair Display",
      body: "Cormorant Garamond",
      script: "Great Vibes",
    },
    decorAssets: { petals: false, sparkles: true, motif: "flourish" },
    content: {
      eyebrow: "Housewarming",
      heroHeadline: "The First Lamp Is Lit",
      heroSubline: "An evening in our new home — {date}",
      invitationLetter:
        "The {names} family invites you to our new home on {date}.{venue} We'll light the first lamp together and eat far too much.",
      storyHeadline: "Our New Home",
      thankYou: "Thank you for blessing our new beginning.",
      hashtagSuffix: "Housewarming",
    },
    isPremium: false,
    sortOrder: 152,
  },

  // --- Baby Shower ---------------------------------------------------------
  {
    name: "Godh Bharai",
    slug: "godh-bharai",
    description: "Rose pink and gold for a traditional godh bharai.",
    category: "traditional",
    eventCategory: "baby-shower",
    colorPalette: {
      primary: "#a8395f",
      secondary: "#fbdde7",
      accent: "#d9a520",
      background: "#fff8fa",
      foreground: "#3d1224",
    },
    fontPairing: {
      display: "Playfair Display",
      body: "Cormorant Garamond",
      script: "Great Vibes",
    },
    decorAssets: { petals: true, sparkles: true, motif: "paisley" },
    content: {
      eyebrow: "Godh Bharai",
      heroHeadline: "Blessings Before The Baby",
      heroSubline: "Join the godh bharai — {date}",
      invitationLetter:
        "Our family invites you to the godh bharai of {names} on {date}.{venue} Come bless the mother-to-be with sweets, songs, and good wishes.",
      storyHeadline: "Waiting For You",
      thankYou: "Thank you for filling the house with blessings.",
      hashtagSuffix: "GodhBharai",
    },
    isPremium: false,
    sortOrder: 160,
  },
  {
    name: "Little Star",
    slug: "little-star",
    description: "Soft yellow and grey, calm and contemporary.",
    category: "minimal",
    eventCategory: "baby-shower",
    colorPalette: {
      primary: "#6b6f76",
      secondary: "#fdf0cc",
      accent: "#e8c05a",
      background: "#ffffff",
      foreground: "#2c2f34",
    },
    fontPairing: { display: "Playfair Display", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "none" },
    content: {
      eyebrow: "Baby Shower",
      heroHeadline: "A Little Star Is Coming",
      heroSubline: "Brunch, games, and a very round belly — {date}",
      invitationLetter:
        "We're throwing a baby shower for {names} on {date}.{venue} Come eat, play silly games, and help us count down.",
      storyHeadline: "Waiting For You",
      thankYou: "Thank you for celebrating before the big arrival.",
      hashtagSuffix: "BabyShower",
    },
    isPremium: false,
    sortOrder: 161,
  },
  {
    name: "Bloom & Bump",
    slug: "bloom-and-bump",
    description: "Blush florals and sage for a garden baby shower.",
    category: "fusion",
    eventCategory: "baby-shower",
    colorPalette: {
      primary: "#a1566b",
      secondary: "#f7e2e6",
      accent: "#8fa07a",
      background: "#fdf8f7",
      foreground: "#3b2129",
    },
    fontPairing: {
      display: "Playfair Display",
      body: "Cormorant Garamond",
      script: "Great Vibes",
    },
    decorAssets: { petals: true, sparkles: false, motif: "botanical" },
    content: {
      eyebrow: "Baby Shower",
      heroHeadline: "Bloom Before The Bump",
      heroSubline: "An afternoon in the garden — {date}",
      invitationLetter:
        "Join us in the garden for the baby shower of {names} on {date}.{venue} Flowers, cake, and blessings for the parents-to-be.",
      storyHeadline: "Waiting For You",
      thankYou: "Thank you for showering us with love before the big day.",
      hashtagSuffix: "BabyShower",
    },
    isPremium: false,
    sortOrder: 162,
  },
];
