export const SECTION_ORDER = [
  "ENVELOPE",
  "HERO",
  "COUNTDOWN",
  "STORY",
  "TIMELINE",
  "GALLERY",
  "VENUE",
  "RSVP",
  "REGISTRY",
  "INSTAGRAM",
  "THANK_YOU",
];

export const THEMES = [
  {
    name: "Royal",
    slug: "royal",
    description: "Maroon, gold, and ivory — wax seals and flourish ornaments.",
    colorPalette: {
      primary: "#7a2e2e",
      secondary: "#f3d9d9",
      accent: "#c9942a",
      background: "#faf3ea",
      foreground: "#3a1414",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: true, motif: "flourish" },
    isPremium: false,
    sortOrder: 0,
  },
  {
    name: "Traditional",
    slug: "traditional",
    description: "Deep red and gold with classic Indian motifs.",
    colorPalette: {
      primary: "#8a1f1f",
      secondary: "#ffe8a0",
      accent: "#b8860b",
      background: "#fff8ec",
      foreground: "#2a1206",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: false, motif: "paisley" },
    isPremium: false,
    sortOrder: 1,
  },
  {
    name: "Luxury",
    slug: "luxury",
    description: "Black and gold with sharp, editorial typography.",
    colorPalette: {
      primary: "#111111",
      secondary: "#d4af37",
      accent: "#d4af37",
      background: "#0e0e0e",
      foreground: "#f5f0e6",
    },
    fontPairing: { display: "Playfair Display", body: "EB Garamond", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "geometric" },
    isPremium: true,
    sortOrder: 2,
  },
  {
    name: "Minimal",
    slug: "minimal",
    description: "Clean whitespace, quiet typography, understated elegance.",
    colorPalette: {
      primary: "#1a1a1a",
      secondary: "#e5e5e5",
      accent: "#9a9a9a",
      background: "#ffffff",
      foreground: "#1a1a1a",
    },
    fontPairing: { display: "Playfair Display", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: false, motif: "none" },
    isPremium: false,
    sortOrder: 3,
  },
  {
    name: "Modern",
    slug: "modern",
    description: "Bold color blocking with contemporary sans-serif type.",
    colorPalette: {
      primary: "#1f2937",
      secondary: "#f472b6",
      accent: "#f472b6",
      background: "#fafafa",
      foreground: "#111827",
    },
    fontPairing: { display: "Inter", body: "Inter", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "shapes" },
    isPremium: false,
    sortOrder: 4,
  },
  {
    name: "Temple",
    slug: "temple",
    description: "Stone and saffron tones inspired by temple architecture.",
    colorPalette: {
      primary: "#9a4b1f",
      secondary: "#f2c14e",
      accent: "#7a2e2e",
      background: "#fdf1df",
      foreground: "#3a1f0d",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: false, motif: "temple-arch" },
    isPremium: true,
    sortOrder: 5,
  },
  {
    name: "Palace",
    slug: "palace",
    description: "Jewel-toned emerald and gold with regal framing.",
    colorPalette: {
      primary: "#0f3d2e",
      secondary: "#c9942a",
      accent: "#c9942a",
      background: "#f6f4ea",
      foreground: "#0f2418",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "jali" },
    isPremium: true,
    sortOrder: 6,
  },
  {
    name: "Beach",
    slug: "beach",
    description: "Sandy neutrals and ocean blue for destination weddings.",
    colorPalette: {
      primary: "#1d4e6b",
      secondary: "#f4e3c1",
      accent: "#e0895f",
      background: "#fbf7ee",
      foreground: "#1d2b33",
    },
    fontPairing: { display: "Playfair Display", body: "EB Garamond", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: false, motif: "waves" },
    isPremium: false,
    sortOrder: 7,
  },
  {
    name: "Floral",
    slug: "floral",
    description: "Soft botanical illustrations in blush and sage.",
    colorPalette: {
      primary: "#5c7a3a",
      secondary: "#f3d9d9",
      accent: "#c9942a",
      background: "#fdf8f2",
      foreground: "#2f3a20",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: false, motif: "botanical" },
    isPremium: false,
    sortOrder: 8,
  },
  {
    name: "Pastel",
    slug: "pastel",
    description: "Powder pink and lilac, soft and dreamy.",
    colorPalette: {
      primary: "#a78bca",
      secondary: "#f9d5e5",
      accent: "#f9d5e5",
      background: "#fdfaff",
      foreground: "#3a2f4a",
    },
    fontPairing: { display: "Playfair Display", body: "Cormorant Garamond", script: "Great Vibes" },
    decorAssets: { petals: true, sparkles: true, motif: "confetti" },
    isPremium: false,
    sortOrder: 9,
  },
  {
    name: "Dark Luxury",
    slug: "dark-luxury",
    description: "Charcoal and champagne gold with dramatic shimmer.",
    colorPalette: {
      primary: "#c9a24b",
      secondary: "#2a2a2a",
      accent: "#c9a24b",
      background: "#141414",
      foreground: "#f2ead8",
    },
    fontPairing: { display: "Playfair Display", body: "EB Garamond", script: "Great Vibes" },
    decorAssets: { petals: false, sparkles: true, motif: "shimmer" },
    isPremium: true,
    sortOrder: 10,
  },
];

// No bundled "Studio Library" tracks: shipping placeholder mp3 URLs with no
// actual audio file behind them (the original state of this list) silently
// breaks music for anyone who picks one — the button shows up but nothing
// plays. Real tracks need real licensed audio files hosted somewhere; add
// them via /admin/music with a working URL once you have one.
export const MUSIC_TRACKS: {
  title: string;
  artist: string;
  url: string;
  mood: string;
  isPremium: boolean;
}[] = [];
