"use client";
import { useState, useTransition } from "react";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { prepareInstagramConnectionAction, checkInstagramConnectionAction } from "@/lib/actions/instagram-connect";
export function InstagramConnectDialog({invitationId,open,onOpenChange,onReady}:{invitationId:string;open:boolean;onOpenChange:(open:boolean)=>void;onReady:()=>void}){
 const [connection,setConnection]=useState<{message:string;profileUrl:string;dmUrl:string}|null>(null); const [pending,start]=useTransition();
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[85svh] overflow-y-auto"><DialogHeader><DialogTitle>Connect your Instagram account</DialogTitle><DialogDescription>Follow SK Digital and connect the account you follow from. Your website content stays in this draft.</DialogDescription></DialogHeader><div className="grid gap-3 text-sm"><button disabled={pending} className="rounded-lg border p-3" onClick={()=>start(async()=>{const result=await prepareInstagramConnectionAction(invitationId);if(result.success)setConnection(result.data);else toast.error(result.error);})}>{connection?"Generate a new connection code":"Get connection code"}</button>{connection&&<><a className="rounded-lg border p-3" href={connection.profileUrl} target="_blank" rel="noreferrer">1. Follow our Instagram</a><p>2. Copy this message and send it from your following account:</p><code className="break-all rounded-lg bg-violet-50 p-3">{connection.message}</code><button className="rounded-lg border p-2" onClick={()=>void navigator.clipboard.writeText(connection.message).then(()=>toast.success("Connection message copied.")).catch(()=>toast.message("Select the message to copy it."))}>Copy connection message</button><a className="rounded-lg bg-violet-700 p-3 text-center text-white" href={connection.dmUrl} target="_blank" rel="noreferrer">Open Instagram messages</a><p className="text-xs text-muted-foreground">The code expires after 15 minutes. Instagram sends your private editor link after verifying your follow.</p></>}<button disabled={pending} className="rounded-lg border p-3" onClick={()=>start(async()=>{const result=await checkInstagramConnectionAction(invitationId);if(!result.success){toast.error(result.error);return;}if(result.data.ready){toast.success(result.data.message);onOpenChange(false);onReady();}else toast.message(result.data.message);})}>I sent the message · Check connection</button></div></DialogContent></Dialog>;
}
